name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # To avoid "Shallow clone detected" error in SonarCloud report

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: make install

      - name: Check Code Style
        run: make phpcs

      - name: Units Tests
        run: make tests

      - name: PHP 7.3 Compatibility
        run: make php73compatibility

      - name: PHP 8.1 Compatibility
        run: make php81compatibility

      - name: PHP Static Analyzis
        run: make analyze
